add test results on github

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -63,6 +63,11 @@ jobs:
         uses: gradle/actions/setup-gradle@v6
       - name: Test TurtleProv with Gradle
         run: ./gradlew :turtleprov:${{ matrix.target }}
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/*/TEST-*.xml'
 
   burp-test:
     needs: build
@@ -86,3 +91,8 @@ jobs:
         uses: gradle/actions/setup-gradle@v6
       - name: Test BURP with Gradle
         run: ./gradlew :burp:test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
